 version: '3'

 services:

   os:
     image: centos
     ports:
       - "80:80"
   database:
     image: mysql:5.7
     ports:
       - "3306:3306"
     environment:
      MYSQL_DATABASE: 'db'
#      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'niket'
#      # You can use whatever password you like
      MYSQL_PASSWORD: 'Admin@123'
#      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Admin@1234'
