FROM centos:latest
RUN mkdir -p ~/new-dir1
RUN useradd -ms /bin/bash cloud_user
#RUN mkdir -p ~/new-dir2
RUN mkdir -p /etc/myconf
RUN echo "some configration" >> /etc/myconf/myconf.conf
USER cloud_user
RUN mkdir -p ~/new-dir2

